#!/bin/bash
#run me to reinstall backup and virus scan scripts and check that they are enabled and functioning
if [[ ! -d "$HOME/bin" ]]; then
  echo "Creating $HOME/bin."
  mkdir "$HOME/bin"
  echo "if ( ! echo \"\$PATH\" | grep -q \"/pub/scripts\" ); then" >> "$HOME/.bashrc"
  echo "  export PATH=\"\$HOME/bin:\$PATH\"" >> "$HOME/.bashrc"
  echo "fi" >> "$HOME/.bashrc"
  echo "You need to relog for changes to \$PATH to take effect." 
fi

pushd "$HOME/bin" > /dev/null

if ! (which backup.sh > /dev/null); then
  echo "Getting backup.sh from github" 
  wget "https://github.com/hp6000x/backup.sh/blob/master/backup.sh"
  chmod 755 backup.sh
  echo "You need to edit $HOME/bin/backup.sh to suit your system. Go to https://github.com/hp6000x/backup.sh for details."
  exit
fi

if ! (which enable_avscan > /dev/null); then
  echo "Getting enable_avscan from github"
  wget "https://github.com/hp6000x/enable_avscan/blob/master/enable_avscan"
  chmod 755 enable_avscan
fi

if ! (which enable_docs_backup > /dev/null); then
  echo "Getting enable_docs_backup from github"
  wget "https://github.com/hp6000x/docsbackup/blob/master/enable_docs_backup"
  chmod 755 enable_docs_backup
fi

if ! (which watchlogtails > /dev/null); then
  echo "Getting watchlogtails from github"
  wget "https://github.com/hp6000x/watchlogtails/blob/master/viewlogtails"
  chmod 755 viewlogtails
  wget "https://github.com/hp6000x/watchlogtails/blob/master/watchlogtails"
  chmod 755 watchlogtails
fi  

popd > /dev/null

echo "Installing daily backup script..."
backup.sh -i
"echo Installing AV scan scripts..."
enable_avscan
echo "Installing weekly docs backup script..."
enable_docs_backup 

echo "Launching daily backup script..."
sudo /etc/cron.daily/backup &
echo "Launching documents backup scripts"
for a in /etc/cron.weekly/docs-backup-*; do 
  if [[ -e "$a" ]]; then
    sudo "$a" &
  fi
done
for i in daily weekly monthly; do
  echo "Launching $i AV scan script..."
  sudo /etc/cron.$i/antivirus_scan &
done
echo "Done. Now running watchlogtails to view output"
echo "Hit ENTER to continue..."
read dummy
watchlogtails
exit 0
